config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "lists#index"
  resources :lists do
    resources :bookmarks
    resources :reviews
  end
  resources :movies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie, dependent: :destroy
  belongs_to :list
  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie_id, :list_id, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :reviews, dependent: :destroy
  validates :name, uniqueness: true
  has_many :movies, through: :bookmarks
  has_one_attached :photo
  # has_and_belongs_to_many :movies
  # has many reviews of the list!
  # review would have 1 list
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :lists, through: :bookmarks
  validates :title, :overview, presence: true
  validates :title, :overview, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def index
    @bookmarks = Bookmark.all
  end

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.find(params[:id])
  end

  def update
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.find(params[:id])
    @bookmark.update(bookmark_params)
    redirect_to list_path(@list)
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path, status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @review = Review.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to list_path(@list)
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    @list.update(list_params)
    redirect_to list_path(@list)
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end


end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @review = Review.new(review_params)
    @review.list = @list
    if @review.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment, :list_id)

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/edit.html.erb
<div class="container">
  <h1>New Bookmark</h1>
  <%= simple_form_for([@list, @bookmark]) do |f| %>
    <%= f.association :movie %>
    <%= f.input :comment %>
    <%= f.submit %>
  <% end %>
</div>

app/views/bookmarks/index.html.erb
<div class="container">
  <h1>Bookmarks</h1>
</div>

app/views/bookmarks/new.html.erb
<div class="container">
  <h1>New Bookmark</h1>
  <%= simple_form_for([@list, @bookmark]) do |f| %>
    <%= f.association :movie %>
    <%= f.input :comment %>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<div class="container">
  <h1>New list</h1>
  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file  %>
    <%= f.submit %>
  <% end %>
</div>

app/views/lists/index.html.erb
<div class="banner banner-background-image">
  <div class="container">
    <h1>Create <strong>your top movie lists</strong>!</h1>
    <p>Find your top netflix and chill movies</p>
    <%= link_to 'Create list', new_list_path, class: "btn btn-gradient" %>
  </div>
</div>

<div class="container">
  <h1>Lists</h1>
  <ul>
    <% @lists.each do |list| %>
      <%= link_to list do %>
        <div class="card-trip">
            <% if list.photo.attached?%>
              <%= cl_image_tag list.photo.key %>
            <% end %>
            <div class="card-trip-infos">
              <div>
              <h2><%= list.name %></h2>
              </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h1>New list</h1>
  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file  %>
    <%= f.submit %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="container">

  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @list.photo.key, height: 300, crop: :fill %>')">
    <h1><%= @list.name %></h1>
    <%= link_to "Edit", edit_list_path(@list),
    data: {turbo_method: :edit} %>
    <%= link_to "Delete",
    list_path(@list),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
  </div>

  <div class="movie_review">
    <div class="movies">
      <h2>Movies</h2>
      <ul>
        <% @list.bookmarks.each do |bookmark| %>
          <div class="card-product">
            <img src="<%= bookmark.movie.poster_url %>" />
            <div class="card-product-infos">
              <h4><%=bookmark.movie.title %></h4>
              <p><%=bookmark.comment%></p>
              <%= link_to "Edit", edit_list_bookmark_path(bookmark.list, bookmark),
              data: {turbo_method: :edit} %>
                <%= link_to "Delete",
              list_bookmark_path(bookmark.list, bookmark),
              data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
            </div>
          </div>
        <% end %>
      </ul>
    </div>

    <div class="reviews">
      <%= link_to 'Add Movie', new_list_bookmark_path(@list, @book), class: "btn btn-gradient" %>

      <div class="form-group">
        <h3>Review Movie list</h3>
        <%= simple_form_for([@list, @review]) do |f| %>
          <%= f.input :rating %>
          <%= f.input :comment %>
          <%= f.submit %>
        <% end %>
      </div>

      <div class="review-list">
        <h3>Reviews</h3>
          <% @list.reviews.each do |review| %>
            <div class="card-product">
              <div class="card-product-infos">
                <p>Rating:<%= review.rating %> </p>
                <p><%= review.comment %> </p>
              </div>
            </div>
          <% end %>
      </div>
    </div>
  </div>








</div>

app/views/movies/index.html.erb
<div class="container">
  <h1>Movies</h1>
  <ul>
    <% @movies.each do |movie| %>
    <h3><%= link_to "#{movie.title}", "/movies/#{movie.id}" %></h3>
    <% end %>
  </ul>
</div>

app/views/movies/show.html.erb
<div class="container">
  <h1>Title:<%= @movie.title %></h1>
  <p>Overview:<%= @movie.overview %></p>
  <p>Rating:<%= @movie.rating %></p>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "Home", lists_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
          </li>
          <li class="nav-item">
            <%= link_to 'Lists', lists_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Movies', movies_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'New List', new_list_path, class: "nav-link" %>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>